apiVersion: v1
kind: Service
metadata:
  name: tathagat-bug-test-kubertest-yaml-svc
spec:
  type: {{.Values.serviceType}}
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.serviceTargetPort}}
      protocol: TCP
  selector:
    app: {{.Values.name}}
