apiVersion: v1
kind: ServiceList
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: my-service-1
    labels:
      environment: true
      app: nginx    
  spec:
    selector:
      app: MyApp1
    ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
- apiVersion: v1
  kind: Service
  metadata:
    name: my-service-2
    labels:
      environment: 100
      app: nginx
    annotations:
      harness.io/skip-versioning: "true"
      harness.io/direct-apply: "true"
  spec:
    selector:
      app: MyApp2
    ports:
      - protocol: TCP
        port: 90
        targetPort: 9476
